web:
  image: nginx
  volumes:
   - ./src:/usr/share/nginx/html
   - ./nginx/conf.d:/etc/nginx/conf.d
  ports:
   - "8080:80"
  environment:
   - DOMAIN_URL=https://api.scaleway.com/domain/v2alpha2/
   - ACCOUNT_URL=https://api.scaleway.com/account/v1/
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"